In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/machine learning/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df.drop(columns=['PassengerId', 'Name', 'SibSp',	'Parch', 'Ticket', 'Cabin', 'Embarked' ], axis='columns',inplace=True)
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [ ]:
inputs=df.drop('Survived',axis='columns')
target=df.Survived

In [ ]:
dummies= pd.get_dummies(inputs.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [ ]:
inputs=pd.concat([inputs,dummies],axis='columns')
inputs

Pclass     Sex   Age     Fare  female  male
0         3    male  22.0   7.2500       0     1
1         1  female  38.0  71.2833       1     0
2         3  female  26.0   7.9250       1     0
3         1  female  35.0  53.1000       1     0
4         3    male  35.0   8.0500       0     1
..      ...     ...   ...      ...     ...   ...
886       2    male  27.0  13.0000       0     1
887       1  female  19.0  30.0000       1     0
888       3  female   NaN  23.4500       1     0
889       1    male  26.0  30.0000       0     1
890       3    male  32.0   7.7500       0     1

[891 rows x 6 columns]

In [ ]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs

Pclass   Age     Fare  female
0         3  22.0   7.2500       0
1         1  38.0  71.2833       1
2         3  26.0   7.9250       1
3         1  35.0  53.1000       1
4         3  35.0   8.0500       0
..      ...   ...      ...     ...
886       2  27.0  13.0000       0
887       1  19.0  30.0000       1
888       3   NaN  23.4500       1
889       1  26.0  30.0000       0
890       3  32.0   7.7500       0

[891 rows x 4 columns]

In [ ]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [ ]:
inputs.Age= inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(inputs, target,test_size=0.2)


In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [ ]:
model.fit(x_train,y_train)

GaussianNB()

In [ ]:
model.score(x_test, y_test)

0.8100558659217877

In [ ]:
x_test[:10]

Pclass        Age     Fare  female
347       3  29.699118  16.1000       1
628       3  26.000000   7.8958       0
151       1  22.000000  66.6000       1
317       2  54.000000  14.0000       0
456       1  65.000000  26.5500       0
108       3  38.000000   7.8958       0
193       2   3.000000  26.0000       0
162       3  26.000000   7.7750       0
491       3  21.000000   7.2500       0
415       3  29.699118   8.0500       1

In [ ]:
y_test[:10]

347    1
628    0
151    1
317    0
456    0
108    0
193    1
162    0
491    0
415    0
Name: Survived, dtype: int64

In [ ]:
model.predict(x_test[:10])

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
model.predict_proba(x_test[:10])

array([[0.45694971, 0.54305029],
       [0.96431697, 0.03568303],
       [0.02815965, 0.97184035],
       [0.89217007, 0.10782993],
       [0.52095084, 0.47904916],
       [0.9656618 , 0.0343382 ],
       [0.82745455, 0.17254545],
       [0.96430238, 0.03569762],
       [0.96085967, 0.03914033],
       [0.45542304, 0.54457696]])

In [ ]:
#cross validtn
from sklearn.model_selection import cross_val_score
fv=cross_val_score(GaussianNB(),x_train,y_train,cv=5)
fv

array([0.72727273, 0.77622378, 0.73943662, 0.78873239, 0.75352113])

In [ ]:
import numpy as np
np.average(fv)

0.7570373288683148